### PR TITLE
Doctrine integration for development

### PR DESCRIPTION
**Pull request by Rastusik**
I'm not sure whether this makes sense for the package maintainers, but I needed to do some performance testing using Doctrine, so I integrated Doctrine into the development stack. I also made some cleanups in the services configs and in the extension (best practise says, that Symfony bundles shouldn't use autoconfiguration and autowiring) ... I also overwrited the EntityManagerHandler to be used from within the application (in the app lifecycle), and I want to register other services which would reset their state into the mechanism. And the last thing - I created a custom docker-compose file for development and performance testing (not sure how you develop this bundle without this) ...

Does it make sense for you to merge this into the bundle, guys?

### CODE REVIEW

**Comment by k911** [comment]
Hello @Rastusik, thanks for your contribution.

I believe some of your work would be beneficial to the project, but you'll need to split changes provided in this pull request for several pull requests regarding specific things 1) for readability 2) because changelog and deployment for this library bases on conventional commit messages. (https://github.com/conventional-changelog/conventional-changelog)

PR to be created from this one:
- Change of code style rules (PHP CS Fixer)
- Change of formatting rules (.editorconfig)
- Symfony Bundle and DI improvements
- Actual features and tests for them (you could write issue with planned specification, and what problem does it solve or your use case)
- Docker configuration improvements

**Comment by Rastusik** [comment]
Hi @k911 , I'm sorry, but I'm quite in a hurry and I will not have time for such splits, at least not for now. I just thought it would make sense to at least try to create a pull request, even if it won't pass... For now I will have to stuck with the custom fork. Thanks anyway

**Comment by k911** [comment]
No problem @Rastusik, in case you find some time, feel free to reopen or propose new PR(s)! :) Thanks for your time and effort!

**Comment by Rastusik** [comment]
Btw, what kind of bothers me is the enforced `native_function_invocation`. Would it be possible to get rid of this rule? I think it's bad for readibility. I'm asking just to know whether it would make sense to create a pull request with disabled enforcing of this rule

**Comment by k911** [comment]
@Rastusik It's ok but we'll need then to import functions and I cannot find php cs fixer option for this.

**Comment by Rastusik** [comment]
@k911 do you think that there will be visible performance impact without importing the functions? I'm not so sure about it

**Comment by k911** [comment]
Yes, there will. If you'll check req/s metrics for this bundle and enable api server, endpoint `localhost:9200/healthz` gives around 80k req/s on i7 4CPU

**Comment by Rastusik** [comment]
how exactly are you testing this? I was testing the healtz endpoint on my docker for mac on an i5 dual core and the results were quite similar in both cases, but far from your number ... what number of workers and reactors are you using ? how exactly are you testing? I was only trying this: `ab -c 100 -n 1000 -l http://localhost:9200/healtz` and I was getting cca 700 req/s in both cases, although the numbers also tended to be lower as well ... when I'm testing against a custom endpoint with 10 mysql inserts and one read with limit 10 and sorting, using doctrine, there are no differences... I'm doing the doctrine test with 90 workers just to fully utilize the CPU... so, maybe I'm doing something wrong, but if not, I don't see any performance boost while using `native_function_invocation`. Feel free to correct me if I'm wrong in the way of testing...

**Comment by k911** [comment]
Sorry @Rastusik it would be better to create separate issue discussing perfomance, feel free to open it. I'm using `wrk` and running natively, not in docker, to measure request per second metric provided by this tool. I'll try to record it tommorrow. Note: `healthz` endpoint does basically nothing, when you are connecting to mysql database you won't get near this number.

**Comment by Rastusik** [comment]
I know what the difference is btween the `healtz` endpoint and a real app with database connection. My point was, that the `native_function_invocation` micro optimisation doesn't make any sense in real world apps. I'll try the `wrk` tool, thanks for the tip

**Comment by k911** [comment]
@Rastusik It may not be relevant in most real world applications, but libraries are different, since you don't know what people use it for.

**Comment by k911** [comment]
@Rastusik 
[asciicast](https://asciinema.org/a/784IbxZwx0vDeLYsrojxX85yv)

**Comment by Rastusik** [comment]
@k911  thank you for the guide, I was able to reproduce your setup. There were two funny things:
1) with docker for mac, I got only 3 000 rps on my dualcore macbook pro :)
2) wiiith PHP 7.3 from HomeBrew, I was able to get 33 000 rps ... which is closer tou your numbers and makes sense I think (my mb pro is a 2013 model)... but the important thing ... I got the same results with `native_function_invocation` on and off :) there was no visible performance impact ...

**Pull request closed without merging**
