### PR TITLE
fix for log collecting in symfony profiler

### LINKED ISSUE #241: Profiler toolbar doesn't collect logs
**Describe the bug**
Symfony profiler (debug toolbar) doesn't collect logs with symfony-swoole

**Steps To Reproduce**
Enable the profiler toolbar and try to log something during a profiled request. When going to the request profile from the toolbar, the Logs menu item doesn't contain any data.

**Expected behavior**
There should be data in the logs menu item.

### PR DESCRIPTION
**Pull request by Rastusik**
Resolves #241

### CODE REVIEW

**Comment by k911** [comment]
@Rastusik Could you change commit author to yourself?

**Comment by Rastusik** [comment]
sure, I just don't understand how it is possible that the commit is done by you

**Comment by Rastusik** [comment]
@k911 I changed the commit author

**Comment by k911** [comment]
@Rastusik could you please rebase against develop? I've fixed CI use, so you have to run composer upgrade too.

**Comment by Rastusik** [comment]
@k911 done

**Comment by k911** [comment]
Looks fine, but I'd like to test it locally. Hopefully, I'll merge it today.

**Comment by k911** [comment]
@Rastusik After recent updates the `composer.lock` is again in conflict. You have to rebase again since I cannot push to your repo.

**Comment by Rastusik** [comment]
@k911 done

**Comment by k911** [comment]
@Rastusik Thanks for your contribution! Since, several features has been merged recently I'll release all of it after a short testing period (5-7) days.

**Pull request merged**
