### PR TITLE
feat(http_server): add max_request and max_request_grace configuration options

### PR DESCRIPTION
**Pull request by luca-nardelli**
Hi @k911,

First of all, many thanks for the amazing bundle!
I needed to set the `max_request` and `max_request_grace` options from the bundle configuration so I thought of adding them.

I couldn't find any tests related to the configuration parsing and passing to Swoole, should I create one? If so, should I just test the HttpServerConfiguration class or should I also test parsing from Symfony's side?

Let me know, thanks!

### CODE REVIEW

**Comment by k911** [comment]
@luca-nardelli Thanks, it looks ok to me. Just wondering if we shouldn't prefix those options with: `worker_`, so it'd be more clear when using CLI

You can also add them to the https://github.com/k911/swoole-bundle/blob/develop/docs/configuration-reference.md

Currently, there are no unit tests for configuration component and since there is a major refactor going on on feature branch - so I'm fine with changes

**Comment by luca-nardelli** [comment]
Hey, the prefix seems like a good idea to me as it makes the options clearer to understand.

I should have updated the PR with the prefix and with the documentation update as well

**Comment by luca-nardelli** [comment]
Edit: I changed the node definition for worker_max_request_grace to scalarNode so that we can support null as well (with integerNode this was not supported)

**Comment by luca-nardelli** [comment]
Forgot to ran `composer fix`, I updated the PR

**Comment by k911** [comment]
@luca-nardelli Thanks for this contribution, I'll release this soon

**Pull request merged**
