### PR TITLE
Fixed resetting SwooleSessionStorage when Symfony HTTP Cache is used

### PR DESCRIPTION
**Pull request by supersmile2009**
It's a good idea to reset the state regardless of the request being session related or not. There can be different reasons why session storage may get populated, while request may not contain a session.
One of the real world cases that I encountered - use of CacheKernel:
1. CacheKernel gets the original request, which will not be considered as "sessionRelated", because session isn't initialized in there, even if request technically contains session info.
2. If there's no cache entry, Request object is *cloned* and passed to the normal Kernel. Somewhere within that kernel session is initiated and set to SwooleSessionStorage and to Request. Request object is "sessionRelated" now.
3. Request is handled, response is sent.
4. Kernel termination is initiated. But we're out of context of the cloned "sessionRelated" request. All we have is the original Request object with no Session in it.
Result - session storage is not reset. Next request fails, because it tries to initiate a session again with a not cleared SwooleSessionStorage.

### CODE REVIEW

**Comment by k911** [comment]
Please rebase, also could you please create a small reproducer repository, because honestly it looks a little bit like a hack/workaround and I think we should dig a little bit deeper. I think the proper solution then, should be clearing session between step 3 and 4

**Comment by supersmile2009** [comment]
@k911 Test `K911\Swoole\Tests\Feature\SymfonyCacheKernelSessionTest` is a copy of `K911\Swoole\Tests\Feature\SymfonySessionSwooleSessionStorageTest` but running with `APP_ENV=cache`.

The change in `TestAppKernel` simulates what is usually done in `index.php` - Request is passed to be handled by CacheKernel. Sub-requests are handled by the main kernel (TestAppKernel).

https://travis-ci.org/github/k911/swoole-bundle/jobs/715864436 - build with just the test added, new test fails.
https://travis-ci.org/github/k911/swoole-bundle/jobs/715869737 - build with a fix, new test passes.

**Comment by supersmile2009** [comment]
Another solution would be changing K911\Swoole\Bridge\Symfony\HttpFoundation\Session::onKernelTerminate to `kernel.finish_request`.

**Comment by k911** [comment]
Yeah, @supersmile2009 that's it. I think, I've created this listener and took Symfony's one as a base, however I see now Symfony is a little bit different https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/EventListener/AbstractSessionListener.php and what you're saying that we should use onFinishRequest event is probably correct solution

**Comment by k911** [comment]
@supersmile2009 I see that you have to run just `composer fix` and it will be working

**Comment by supersmile2009** [comment]
> @supersmile2009 I see that you have to run just `composer fix` and it will be working

@k911 done

**Comment by k911** [comment]
Thanks @supersmile2009

**Pull request merged**
