### PR TITLE
add suggestion to use pixelfederation/doctrine-resettable-em-bundle

### LINKED ISSUE #185: Replace entity manager handler with doctrine resettable em bundle
**Is your feature request related to a problem? Please describe.**
The problem of the implemented entity manager handler is, that when an exception occurs in the entity manager, it gets closed and it won't be reset automatically. 

**Describe the solution you'd like**
I've implemented a resettable entity manager handler in this bundle: https://github.com/pixelfederation/doctrine-resettable-em-bundle . I would like to remove the current entity manager handler and suggest to integrate the bundle. 

**Describe alternatives you've considered**
Normally I would just made a pull request to get the bundle's code into this swoole bundle, but the problem is, that I needed the resetting outside of swoole bundle (in Symfony Messenger worker context) . 

What do you think, @k911  ?

In addition to that (not sure whether I should open another issue, so I'm briefly mentioning it here) - I have a fork of your repository (https://github.com/pixelfederation/swoole-bundle) and I would like to port the features from the fork into your bundle. Feature after feature, separately, so the process and the features are understandable. What do you think about that? I couldn't do it before, because I needed to make some experiments and get our app up and running, so it was faster to proceed separately.

### PR DESCRIPTION
**Pull request by Rastusik**
Composer - added suggestion to use pixelfederation/doctrine-resettable-em-bundle to be able to recover from entity manager errors.
This was made according to #185 , no code needed to be changed for the integration

Closes #185

### CODE REVIEW

**Comment by Rastusik** [comment]
not sure whether I can do something with the failed test

**Comment by k911** [comment]
Thanks, @Rastusik I also recommend adding at least two or three sentences in the docs directory, what do you think?

**Comment by Rastusik** [comment]
no problem, will do

**Comment by k911** [comment]
Thanks, @Rastusik, It'll be released soon.

**Pull request merged**
